<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto

namespace Tensorflow\Serving;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Metadata for an inference request such as the model name and version.
 *
 * Generated from protobuf message <code>tensorflow.serving.ModelSpec</code>
 */
class ModelSpec extends \Google\Protobuf\Internal\Message
{
    /**
     * Required servable name.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * Optional version. If unspecified, will use the latest (numerical) version.
     * Typically not needed unless coordinating across multiple models that were
     * co-trained and/or have inter-dependencies on the versions used at inference
     * time.
     *
     * Generated from protobuf field <code>.google.protobuf.Int64Value version = 2;</code>
     */
    private $version = null;

    public function __construct() {
        \GPBMetadata\Model::initOnce();
        parent::__construct();
    }

    /**
     * Required servable name.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Required servable name.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Optional version. If unspecified, will use the latest (numerical) version.
     * Typically not needed unless coordinating across multiple models that were
     * co-trained and/or have inter-dependencies on the versions used at inference
     * time.
     *
     * Generated from protobuf field <code>.google.protobuf.Int64Value version = 2;</code>
     * @return \Google\Protobuf\Int64Value
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Optional version. If unspecified, will use the latest (numerical) version.
     * Typically not needed unless coordinating across multiple models that were
     * co-trained and/or have inter-dependencies on the versions used at inference
     * time.
     *
     * Generated from protobuf field <code>.google.protobuf.Int64Value version = 2;</code>
     * @param \Google\Protobuf\Int64Value $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Int64Value::class);
        $this->version = $var;

        return $this;
    }

}

