<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto

namespace GPBMetadata;

class Model
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a770a0b6d6f64656c2e70726f746f121274656e736f72666c6f772e7365" .
            "7276696e6722470a094d6f64656c53706563120c0a046e616d6518012001" .
            "2809122c0a0776657273696f6e18022001280b321b2e676f6f676c652e70" .
            "726f746f6275662e496e74363456616c75654203f80101620670726f746f" .
            "33"
        ));

        static::$is_initialized = true;
    }
}

