<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prediction_service.proto

namespace GPBMetadata;

class PredictionService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Predict::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa4010a1870726564696374696f6e5f736572766963652e70726f746f12" .
            "1274656e736f72666c6f772e73657276696e6732670a1150726564696374" .
            "696f6e5365727669636512520a075072656469637412222e74656e736f72" .
            "666c6f772e73657276696e672e50726564696374526571756573741a232e" .
            "74656e736f72666c6f772e73657276696e672e5072656469637452657370" .
            "6f6e73654203f80101620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

