<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resource_handle.proto

namespace GPBMetadata;

class ResourceHandle
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad0010a157265736f757263655f68616e646c652e70726f746f120a7465" .
            "6e736f72666c6f77226d0a0e5265736f7572636548616e646c65120e0a06" .
            "64657669636518012001280912110a09636f6e7461696e65721802200128" .
            "09120c0a046e616d6518032001280912110a09686173685f636f64651804" .
            "2001280412170a0f6d617962655f747970655f6e616d6518052001280942" .
            "340a186f72672e74656e736f72666c6f772e6672616d65776f726b421352" .
            "65736f7572636548616e646c6550726f746f5001f80101620670726f746f" .
            "33"
        ));

        static::$is_initialized = true;
    }
}

