<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensor_shape.proto

namespace GPBMetadata;

class TensorShape
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad8010a1274656e736f725f73686170652e70726f746f120a74656e736f" .
            "72666c6f77227a0a1054656e736f72536861706550726f746f122d0a0364" .
            "696d18022003280b32202e74656e736f72666c6f772e54656e736f725368" .
            "61706550726f746f2e44696d12140a0c756e6b6e6f776e5f72616e6b1803" .
            "200128081a210a0344696d120c0a0473697a65180120012803120c0a046e" .
            "616d6518022001280942320a186f72672e74656e736f72666c6f772e6672" .
            "616d65776f726b421154656e736f72536861706550726f746f735001f801" .
            "01620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

