<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensor_shape.proto

namespace Tensorflow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * One dimension of the tensor.
 *
 * Generated from protobuf message <code>tensorflow.TensorShapeProto.Dim</code>
 */
class TensorShapeProto_Dim extends \Google\Protobuf\Internal\Message
{
    /**
     * Size of the tensor in that dimension.
     * This value must be >= -1, but values of -1 are reserved for "unknown"
     * shapes (values of -1 mean "unknown" dimension).  Certain wrappers
     * that work with TensorShapeProto may fail at runtime when deserializing
     * a TensorShapeProto containing a dim value of -1.
     *
     * Generated from protobuf field <code>int64 size = 1;</code>
     */
    private $size = 0;
    /**
     * Optional name of the tensor dimension.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';

    public function __construct() {
        \GPBMetadata\TensorShape::initOnce();
        parent::__construct();
    }

    /**
     * Size of the tensor in that dimension.
     * This value must be >= -1, but values of -1 are reserved for "unknown"
     * shapes (values of -1 mean "unknown" dimension).  Certain wrappers
     * that work with TensorShapeProto may fail at runtime when deserializing
     * a TensorShapeProto containing a dim value of -1.
     *
     * Generated from protobuf field <code>int64 size = 1;</code>
     * @return int|string
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Size of the tensor in that dimension.
     * This value must be >= -1, but values of -1 are reserved for "unknown"
     * shapes (values of -1 mean "unknown" dimension).  Certain wrappers
     * that work with TensorShapeProto may fail at runtime when deserializing
     * a TensorShapeProto containing a dim value of -1.
     *
     * Generated from protobuf field <code>int64 size = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->size = $var;

        return $this;
    }

    /**
     * Optional name of the tensor dimension.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Optional name of the tensor dimension.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

}

